[package]
name = "cineteca"
version = "0.1.0"
edition = "2024"

[dependencies]
cursive = "0.21.1"
ffmpeg-next = "8.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
time = { version = "0.3.44", features = ["serde"] }
walkdir = "2.5.0"
