name: "Check code style"

on: pull_request

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: check format nix
        run: nix build .#checks.x86_64-linux.formatting-nix
      - name: check format rust
        if: success() || failure() #run even if checking nix files failed
        run: nix build .#checks.x86_64-linux.formatting-rust

  check-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: check linting rust
        run: nix build .#checks.x86_64-linux.linting-rust
